USE [master]
GO

/****** Object:  Database [SportsDatabase]    Script Date: 10/10/2018 12:41:02 AM ******/
DROP DATABASE [SportsDatabase]
GO

/****** Object:  Database [SportsDatabase]    Script Date: 10/10/2018 12:41:02 AM ******/
CREATE DATABASE [SportsDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SportsDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SportsDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SportsDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SportsDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SportsDatabase] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SportsDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SportsDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SportsDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SportsDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SportsDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SportsDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [SportsDatabase] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SportsDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SportsDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SportsDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SportsDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SportsDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SportsDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SportsDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SportsDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SportsDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SportsDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SportsDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SportsDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SportsDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SportsDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SportsDatabase] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SportsDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SportsDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SportsDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [SportsDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SportsDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SportsDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SportsDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SportsDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SportsDatabase] SET QUERY_STORE = OFF
GO

USE [SportsDatabase]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SportsDatabase] SET  READ_WRITE 
GO

